### ISSUE TITLE
I have the same question:Unsynchronized metadata read [1.4.180/3]

### ISSUE THREAD

**Issue by 601193408** [gitbucket/gitbucket#1067]
https://github.com/gitbucket/gitbucket/issues/756

Please help me

**Comment by takezoe** [comment]
@601193408 Try H2 recover tool or [migration tool](https://github.com/gitbucket/h2-migration). When both of them failed, rolled back your GitBucket version or use [GitBucket 3.10.1_h2-1.4.180](https://github.com/gitbucket/gitbucket/releases/tag/3.10.1_h2-1.4.180) instead of GitBucket 3.10.1.
However, h2-1.4.180 version will not be released since the next release, so we recommend that migrate your database using the migration tool mentioned above.

**Comment by 601193408** [comment]
thanks.
