### ISSUE TITLE
Default assignee?

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [gitbucket/gitbucket#1078]
I would be happy if gitbucket has a feature that assigns the person who makes an issue to an assignee by default.

Best,

**Comment by McFoggy** [comment]
Honestly I would not be happy with such a feature.
It is not because you report an issue that you will or have to handle it. 
It is probably true if you are the only member of a project but even in this case if you assign by default then you loose the possibility to filter on them. 
When an issue has an assignee, in my understanding of github/gitbucket workflows, is when someone is really looking at the issue or has it in his todo list.

**Comment by HIRANO-Satoshi** [comment]
That's true in many cases, especially with github.

GitBucket is popular in many companies for their closed source projects with limited number of members.

In our case I spend time for assginging myself to my issues, because I write code, fix, write, fix, wite... code I'm in charge of. 

90% of issues I made is my issues. I think that's common to many closed projects.

I wish to have _**an option**_ that assigns myself to my issues automatically.

**Comment by McFoggy** [comment]
Even if it was an option, what is then the purpose of being an assignee?

AFAIK you do not need to be assignee to close issues, so what purpose does the assignment diserve?

**Comment by HIRANO-Satoshi** [comment]
How do you distingush my issues and unassgined issues, if I don't assign myself to my issues?

How do you search my issues?

How do you list unassigned issues?

**Comment by McFoggy** [comment]
> How do you distingush my issues and unassgined issues, if I don't assign myself to my issues?
it is exactly why I challenged the proposal.

With your proposal:
- unassigned issues: will be always empty
- my issues: will contain all the open issues

If you automatically assign issues then the normal "unassigned issue list" becomes "yours issues" list and then you cannot distinguish anymore between the issue you are working one with the ones that are not under consideration yet.

**Comment by HIRANO-Satoshi** [comment]
I found "your issues" filter. I will use it. 

Thanks.

**Comment by takezoe** [comment]
I understand "default assignee" option is useful for some situation. However I expect we want more like "conditional default assignee" in such situation.

We would like to keep GitBucket core as simple as possible. So it's better to provide such situational features as plugin.

**Comment by eprozium** [comment]
this could be done by a plug-in if the API would allow it.

**Comment by pratulw** [comment]
In larger projects and teams this feature would be very useful. When you have multiple components and teams working  on a project it is ideal to have default assignee for each of this. Otherwise there is significant time spent on just doing  this everyday. Most issue tracking systems have this as a default. You could also allow an owner field in labels to do this.

**Comment by HIRANO-Satoshi** [comment]
I no longer need this feature.

**Comment by aadrian** [comment]
> I no longer need this feature.
