### ISSUE TITLE
Can't change a color of a label.

### ISSUE THREAD

**Issue by YoshinoriN** [gitbucket/gitbucket#1152]
**Impacted version**: 3.12

**Problem description**:
Can't change a color of label.

![label](https://cloud.githubusercontent.com/assets/11273093/13739889/1ee0c2f6-ea11-11e5-8b5b-f5f0c9697fe0.gif)

Thanks.

**Comment by maximx1** [comment]
Same in 3.13. It looks like you can save the color changes if you change the name of the label before clicking save. Wild guess, but does [the edit form input](https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/controller/LabelsController.scala#L54) apply [this form mapping](https://github.com/gitbucket/gitbucket/blob/master/src/main/scala/gitbucket/core/controller/LabelsController.scala#L22) when the ajax runs? What I mean by that is that I think that the validation is looking up the name of the label/owner pair as if your edit is actually inputting a brand new label instead of changing an existing one. 

I'm not as familiar with this code structure, so it's really a guess from what I could explore on short notice.
