### ISSUE TITLE
Wrong informations in branch list

### ISSUE THREAD

**Issue by simmyg89** [gitbucket/gitbucket#1167]
This is what the web page present

<img width="690" alt="screen shot 2016-04-08 at 15 20 18" src="https://cloud.githubusercontent.com/assets/1280258/14384933/1694971c-fd9e-11e5-833c-c3f76da2f022.png">

and this is what we really have

<img width="378" alt="screen shot 2016-04-08 at 15 23 01" src="https://cloud.githubusercontent.com/assets/1280258/14384940/1de5bc44-fd9e-11e5-9b41-ee8eefe2fd82.png">

Seems that the master branch in the web page refer to the 39_... branch, but it's not true

Many thanks

**Comment by KrisShannon** [comment]
I don't think this is fixed.

It looks like the real issue is on [line 890]:(/gitbucket/gitbucket/blob/35080a9f3377daeb3ed8cd7316588ed6e2bb07b8/src/main/scala/gitbucket/core/util/JGitUtil.scala#L890)

>   val defaultObject = if (repo.getAllRefs.keySet().contains(defaultBranch)) {

where the keys of the `getAllRefs` all have the 'refs/...' prefixes but the `defaultBranch` doesn't so it never matches and the code falls through to

>   git.branchList().call().iterator().next().getObjectId
