### ISSUE TITLE
Authentication as generic user git failed, public key not found

### ISSUE THREAD

**Issue by Starkmann** [gitbucket/gitbucket#1251]
## Issue
**Impacted version**: 4.1.0

**Deployment mode**: 
I use your docker image and just upgraded to the latest version over 3.14 as recommended.

**Problem description**:
I can not clone/push/pull repositories over the new generic git user. It says:
`16:41:40.367 [sshd-SshServer[124ac145]-nio2-thread-3] 
INFO  o.a.s.s.session.ServerSessionImpl - Server session created from /XXX.XXX.XXX.XXX:51456
16:41:40.621 [sshd-SshServer[124ac145]-nio2-thread-4]
 INFO  g.core.ssh.PublicKeyAuthenticator - authentication as generic user git failed, public key is ambiguous
16:41:40.663 [sshd-SshServer[124ac145]-nio2-thread-5] 
INFO  g.core.ssh.PublicKeyAuthenticator - authentication as generic user git failed, public key not found
16:41:40.705 [sshd-SshServer[124ac145]-nio2-thread-1] I
NFO  g.core.ssh.PublicKeyAuthenticator - authentication as generic user git failed, public key not found
16:41:40.748 [sshd-SshServer[124ac145]-nio2-thread-2] 
INFO  g.core.ssh.PublicKeyAuthenticator - authentication as generic user git failed, public key not found
`

Can not see where i can set the public key for user "git"

**Comment by Starkmann** [comment]
I forgot to mention that we have had already an user called "git". I just deleted the user via the H" console because the administration page was not working for this user.

**Comment by ritschwumm** [comment]
the "generic user git" does not mean a gitbucket user, but an ssh user name as in ```ssh://git@...```.
whenever the ssh user name "git" is used to access a gitbucket repo, gitbucket searches for a (gitbucket) user with the same public key that was used for the ssh connection.

about the messages above:
* ```authentication as generic user git failed, public key is ambiguous``` means you have two different gitbucket users sharing the same public key. gitbucket can't choose which one, so it refuses to grant access. solution: either give them different public keys, or use ```ssh://user@...``` instead of ```ssh://git@...```.
* ```authentication as generic user git failed, public key not found``` means there is no gitbucket user with the public key used to establish the ssh connection. maybe the public key put into gitbucket and tghe one presented by git differ, or maybe the gitbucket user does not exist.

**Comment by Starkmann** [comment]
Thanks. That cleared how it works. 
I deleted all shared keys and now it is working.

There where shared key because we had an "deploy" user to achieve the same what the now introduced "git" user does.

So maybe this could go to the documentation:

- Don't create a user called git
- Don't share key among accounts

**Comment by ritschwumm** [comment]
is it still possible to create a user named "git"? it shouldn't, imho..

**Comment by nazoking** [comment]
anyone can create user called 'git' from user admin page.
we should add validate on creating user name git.
