### ISSUE TITLE
Add sortable priority as an issue attribute

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1396]
GitBucket is not a clone of GitHub no longer. We can improve GitBucket features more than GitHub according to requirements of GitBucket users. One of them is issues. GitHub issues is simple and fits for small projects, but it's not enough for large projects.

As a first step to improve issues, I would like to add a priority attribute as a sortable attribute.

**Comment by imeszaros** [comment]
Is there an ETA for this feature?

**Comment by takezoe** [comment]
@imeszaros No progress yet, but we would raise priority if there are request from users for this feature.

**Comment by imeszaros** [comment]
If you could share your thoughts about the requirements of this feature in greater detail, maybe i could make some progress to implement it. Our team would need this feature badly. :)

**Comment by aadrian** [comment]
@imeszaros 
https://github.com/gitbucket/gitbucket/wiki/Wishlist
Do you need more details?

**Comment by imeszaros** [comment]
For starting, no. Thanks, i've already began coding. :)

**Comment by takezoe** [comment]
@imeszaros Thanks. My idea is simply add dropdown to choose priority. This dropdown should be customizable like milestone.

**Comment by imeszaros** [comment]
I've made some progress on this. Currently, priorities does not have the 'default' flag, since i thought not everyone wants to use prioritization of issues (and to be honest, i did not see this requirement when i started working on this :D). Priority 'description' is also missing currently, but i can add that in no time.

But what priorities do have now is a color like at labels, I thought it's more visual and useful like this. What do you think?

The order of priorities can be edited by mouse dragging the list items. Batch marking, sorting, filtering is also done.

Later this day I'll commit the changes to my fork so you may check it out.

**Comment by aadrian** [comment]
>  I thought it's more visual and useful like this. What do you think?

This sounds very nice but not that important in the beginning . More important would be to:
- have default priorities for each project (like described in the wiki page)
- the users to be able to define their own priorities if they don't fit. Eg. many companies use the "P" coding of priorities instead of names.
