### ISSUE TITLE
gitbucket upgrade

### ISSUE THREAD

**Issue by geeth4sg** [gitbucket/gitbucket#1495]
I have tried to upgrade from 3.11 to latest version, 

1. first upgraded from 3.11 to 3.14 then 4.0. It has been upgraded, but latest repositories are lost, i could not find them in 4.0.

2. Can we in creating repository, is this area a wordpress site?  Can I
create pages with the wordpress admin, etc.  Can I load a theme?  Does GitBucket allow page creation like BitBucket?

3. Need to create docs and wiki for particular repo.

early response much appreciated..

**Comment by aadrian** [comment]
> Does GitBucket allow page creation like BitBucket?

Yes. There's a https://github.com/gitbucket/gitbucket-pages-plugin plug-in for the latest version 4.10 of GitBucket. There are also other useful plug-ins there: http://gitbucket-plugins.github.io/

> Need to create docs and wiki for particular repo.

GitBucket has wiki support since ages. You can deactivate it now however for repos that don't need that: "Toggle repository features" section in http://gitbucket.github.io/gitbucket-news/gitbucket/2016/07/02/gitbucket-4.2.html
