### ISSUE TITLE
Ensure OSS license compliance

### ISSUE THREAD

**Issue by t-tsutsumi** [gitbucket/gitbucket#1575]
Since GitBucket published release (WAR) including dependency libraries, the release must be in accordance with the license of each library.

IMHO, At least should clarify immediately that apply [FOSS License Exception](https://www.mysql.com/jp/about/legal/licensing/foss-exception/) to GitBucket and redistribute MySQL Connector/J licensed under GPLv2.

Currently there are 77 dependencies (including transitive it), so it will take time to finish everything. 😩

**Comment by aadrian** [comment]
> Currently there are 77 dependencies (including transitive it), so it will take time to finish everything. 😩

Version Eye can help with that quite easily:
https://www.versioneye.com/user/projects/592307cc1d263e000ee46140#tab-dependencies

so:
 - mysql-connector-java - the only GPL one.
 - java-diff-utils - unkonwn

All other seem OK and compatible with Apache 2.

----
IMHO support for external DBs could be provided in form of plug-ins.
This way:
 - users could easily implement support for totally new DBs types.
 - we would avoid license problems
 - other plug-ins can depend on them: e.g. backup (since this is DB specific).
