### ISSUE TITLE
Validate password

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1612]
## Issue
**Impacted version**: 4.13 or before

**Problem description**:
GitBucket does not validate password in user registration or password modification that we can use any characters for password currently. Maybe it should limit characters which can be used in password as alphabetical, numerical and some special characters.

**Comment by aadrian** [comment]
@takezoe different companies have different password policies. IMHO GitBucket should not restrict that, but allow an easier integration with SSOs.

**Comment by t-tsutsumi** [comment]
> GitBucket should not restrict that

+1

I think that the essence of this issue is that there are Git clients that do not handle the HTTP authentication password including special characters correctly. (Ref: [gitter room for Japanese](https://gitter.im/gitbucket/gitbucket_ja?at=5924187a9f4f4ab05bf12645))

**Comment by t-tsutsumi** [comment]
For the reference, following is a well-known problem with Git password.

* URL embedded ID/password (Commonly needs URL encode.)
* .netrc (There are characters that cannot be used depending on the Git client.)
* Git Credential Storage
    * Git Credential Manager for Windows <= v1.5.0 (https://github.com/Microsoft/Git-Credential-Manager-for-Windows/pull/259)

**Comment by takezoe** [comment]
> different companies have different password policies.

Anyway, GitBucket can't force that policy. I wish to avoid unnecessary trouble to decrease my effort for support, so I feel necessity of some protection.

**Comment by aadrian** [comment]
> Anyway, GitBucket can't force that policy. 

Exactly! That's why as default GitBucket should not enforce **any** restriction, just document what would be **sane**. This way there's no conflict.

> I wish to avoid unnecessary trouble to decrease my effort for support, so I feel necessity of some protection.

IMHO the best approach would be to make the authentication system as a plug-in, and the default implementation should be always distributed with the app.

Than the LDAP could be a second Authentication plug-in, that users could use or not.

This way:
  - users could easily implement their own SSOs solutions
  - the implementation of users could be company specific or just modifications of existing ones.
  - the existing implementations (default and ldap)  would be a good examples how to make an authentication plug-in.

**Comment by t-tsutsumi** [comment]
> I wish to avoid unnecessary trouble to decrease my effort for support, so I feel necessity of some protection.

Maybe it would be good enough to just document this on the Wiki (FAQ page?).

**Comment by takezoe** [comment]
There are a lot of users behind each GitBucket administrators. We can't expect that all of them read documentation. I'm so tired.
