### ISSUE TITLE
Provides a way to bundle plugins to GitBucket distribution

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#1625]

**Comment by aadrian** [comment]
IMHO for this the first step is to move the plug-ins out of `$GIBUCKET_HOME/plugins/` to another directory. E.g. if there's a `$GITBUCKET_PLUGINS` variable, than to use that instead. 

This way it would be easier to include plug-ins in the Docker image too (since some plug-ins require extra software installed too).

**Comment by takezoe** [comment]
I started to work on this in #1627. I wrote my idea and concerns there.
