### ISSUE TITLE
Operational Concerns With GB

### ISSUE THREAD

**Issue by tundratim** [gitbucket/gitbucket#1637]
Based on a couple of issues I raised earlier today, I attempted to fail back some production GB systems to 4.13 ... which then failed because the database was now at 4.14.

This is a problem in real world production environments.  There has to be a clean way to fail forward- and back when problems are encountered.  

Is there some reason the database has to undergo a change of schema with each release of the code?

**Comment by takezoe** [comment]
As a general theory, If your are using GitBucket for critical purpose, I recommend to test a new release in local or test environment before applying it actually. In addition, you should take backup before upgrading. Then you can rollback to the previous state of upgrading using backup.

As an undesirable way, you can rollback database schema by updating database directly. You can find contents of migration in each version here:
https://github.com/gitbucket/gitbucket/tree/master/src/main/resources/update

and also you should update the `VERSIONS` table as well. If there is no migration to the cancelled version, just update the `VERSIONS` table and it's OK.

> Is there some reason the database has to undergo a change of schema with each release of the code?

Because for makeing new features... but if there are no schema changes in the cancelled version, it might have to be able to rollback without special operation like above. But in any case, 4.14 is not so because it has schema changes.

**Comment by tundratim** [comment]
So we do all those things - test in nonprod, backup the current instance prior to upgrading, etc.

However, the problem is that - once we do upgrade and people start committing their stuff to the newer instance, it becomes very painful to fall back to the older copy.

**Comment by aadrian** [comment]
> However, the problem is that - once we do upgrade and people start committing their stuff to the newer instance, it becomes very painful to fall back to the older copy.

Not really, since there's no need to use an old backup, but to execute the Liquibase downgrade (rollback http://www.liquibase.org/documentation/rollback.html ) step https://github.com/gitbucket/solidbase (every `update` step should have a `rollback` step too)  and than just use the older WAR file and old ```/plugins```.

When updating to a new GitBucket version, Liquibase (Solidbase) will be used at first start to update the DB too the correct "version" https://github.com/gitbucket/gitbucket/tree/master/src/main/resources/update

When performing a **downgrade**, the opposite needs to be achieved: manually or with Liquibase (Solidbase).
