### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by btlogy** [gitbucket/gitbucket#1642]
## Semantic Versioning
**Impacted version**: 4.14.1

**Deployment mode**: RPM

**Problem description**:
First of all: thanks a lot for the amazing work (mostly by @takezoe)! I really love GitBucket. So much easier to deploy and manage than GitLab.

This being said, I've got a little problem for the second time since I'm packaging GitBucket as an RPM. When you follow [semantic versioning](http://semver.org/) (which RPM does), version 4.14.1 will stay newer than most future releases like 4.15!

Could you please consider using 4.15.0 for your next release?

BTW: I could PR a modified rpm spec and init script for el6 if you like it?

That's all :-p

**Comment by takezoe** [comment]
In fact, already GitBucket has been managed under the semantic versioning:

- https://github.com/gitbucket/gitbucket/blob/4.14/build.sbt#L3
- https://github.com/gitbucket/gitbucket/blob/4.14/src/main/scala/gitbucket/core/GitBucketCoreModule.scala#L38
- https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.github.gitbucket%22%20AND%20a%3A%22gitbucket_2.12%22

But it has not been applied to git tags or documents, so I will use an actual version in them since the next release. Thanks for your feedback!

**Comment by btlogy** [comment]
I realized the version was indeed semantic within the app itself!
Thanks a lot. I'm packaging 4.14.1 right now then.

**Comment by btlogy** [comment]
I guess I should have let this issue open so you can track it... Sorry for the mess.
