### ISSUE TITLE
Test with Travis-CI DBs if available.

### ISSUE THREAD

**Issue by aadrian** [gitbucket/gitbucket#1776]
The Integration tests https://github.com/gitbucket/gitbucket/blob/master/src/test/scala/gitbucket/core/GitBucketCoreModuleSpec.scala

use embedded DBs (that are quite slow).

For the Travis-CI only run, please add https://docs.travis-ci.com/user/database-setup/ , so that when running on Travis-CI to use the infrastructure there, instead of downloading and running the embedded DB instances: at least for MySQL, MariaDB and PostgreSQL

Thank you.

**Comment by takezoe** [comment]
Compile and test duration looks about 2-3 minutes and most of them are compilation. Embedded MySQL and PostgreSQL binaries are cached by Travis, extraction of PostgreSQL binary takes  some time but it's less than 10 seconds. It's not so long against the size of GitBucket codebase.

I think that we can't get sufficient benefit by switching databases because bottleneck is compilation.
