### ISSUE TITLE
sidebar repo names text overflows outside the layout and difficult to use for too many repos

### ISSUE THREAD

**Issue by karthikbalu** [gitbucket/gitbucket#1783]
## sidebar repo names text overflows outside the layout and difficult the read the projects and repo names, looks pretty ugly too
**Impacted version**:4.18.0

**Deployment mode**: *standalone app with nginx reverse proxy*

**Problem description**:
- *Sidebar repo names overflows outside the sidebar layout*
- *group could be collapsed to gain some space for repo names and also avoid long scrolling list of repositories, in my case i have 50+ repos* 
![gitbucketsidebar](https://user-images.githubusercontent.com/5414957/33238686-76e22184-d2b8-11e7-91d0-f81d06b31f84.png)

**Comment by karthikbalu** [comment]
Thanks for the great work!, I really appreciate this project and after using gitlab, bitbucket etc., i found gitbucket to be the best for my needs

**Comment by PaulAdams-Conti** [comment]
+1 for this request. Most of us have large monitors and there is plenty of room for the news feed and other information on the right pane, but many of our project names overflow outside the sidebar. Maybe it could be an admin configurable width with set maximum and minimum values so that it can't be too ridiculous.
