### ISSUE TITLE
404 with custom base url

### ISSUE THREAD

**Issue by elion** [gitbucket/gitbucket#1788]
## 404 with custom base url
**Impacted version**: 4.19+

**Deployment mode**: Standalone app behind nginx with custom base url

**Problem description**:
- can not access System Administration, the url `../gitbucket/admin/users` responds with 404
- Another problem is with testing webhook. Somehow hook (name?) is undefined and I get 404 for url
`../settings/hooks/undefined/validate`.

Worked before 4.19.0 upgrade.

**Comment by takezoe** [comment]
When GitBucket isn't deployed document root, some routings didn't work by `CompositeScalatraFilter` bug. This bug was fixed in bcd92916cab7c23f6530009192539e4c1efb9b24.

In addition,  testing web hook causes 404 which you reported in gitter had an another cause. It had been caused by collision of  id attribute  with the bundled notification plugin. This problem was fixed in d15b3fb2f6d2928fb9eb4e400815864d114bb990.

GitBucket 4.19.2 which includes these fixes is available. Could you try it again?
https://github.com/gitbucket/gitbucket/releases/tag/4.19.2

**Comment by elion** [comment]
I can confirm that these issues have been fixed. Many thanks!
