### ISSUE TITLE
White letters on white background ("Light" skins)

### ISSUE THREAD

**Issue by gageas** [gitbucket/gitbucket#1808]
## Issue
**Impacted version**: 4.19.3

**Deployment mode**: standalone app

**Problem description**:
With light skin themes, user's bio and joined date are unreadable because of its color.
Please see attached image.

Color of these fields are seems to be specified by inline style "color: white; ".

https://github.com/gitbucket/gitbucket/blob/54be93b0daf13998858010081c11fc6ccecb969c/src/main/twirl/gitbucket/core/account/main.scala.html#L16

https://github.com/gitbucket/gitbucket/blob/54be93b0daf13998858010081c11fc6ccecb969c/src/main/twirl/gitbucket/core/account/main.scala.html#L23

![screenshot-root - chromium](https://user-images.githubusercontent.com/40446/33991532-4cb7fb6e-e112-11e7-9c84-385222aaa1ad.png)

**Comment by kurdtpage** [comment]
Related to #881

**Comment by RadWolfie** [comment]
I had made a review with AdminLTE demo sidebar layout vs GitBucket's functional sidebar layout. The only difference there is... AdminLTE demo sidebar layout are all links, `<a>` element, in the sidebar which always display with correct theme style. The source of the original color, without inline style, came from `<body>` element. 

I believe it is AdminLTE bug. Since theme's sidebar only has background-color property included, yet no color property had applied for text color to prevent hard to read texts. Here's an example of source missing color property:
https://github.com/gitbucket/gitbucket/blob/58c22274eff6973fe0974813dbdc8521ce12490f/src/main/webapp/assets/vendors/AdminLTE-2.4.2/css/skins/skin-blue-light.css#L59-L63

**Comment by gageas** [comment]
Sorry for commenting closed issue.

Removing inline style is OK, but still problem is.
After removing it, color of these elements are always derivered from gitbucket.css's body {color: #333; }.
It's almost unreadable with Dark skin themes.

Because AdminLTE does not specify text color for these elements in sidebar, as @RadWolfie mentioned (thanks for investigation!)

**Comment by takezoe** [comment]
@gageas That's right. It's ideal if this styles are fixed in AdminLTE, but I suppose it will be done immediately. What's about doing markup texts by `<a>` even if they are not links as workaround?

**Comment by gageas** [comment]
@takezoe I agree with you.
> What's about doing markup texts by <a> even if they are not links as workaround?

I think it is the easiest workaround.
