### ISSUE TITLE
Using keywords in commit do not fire Slack webhook events

### ISSUE THREAD

**Issue by aurelien-defossez** [gitbucket/gitbucket#1880]
## Issue
**Impacted version**: 4.21.2

**Deployment mode**: Standalone app

**Problem description**:
When using keywords in commits to close an issue (e.g. "Close #42"), it successfully closes the issue in the tracker, but it does not fire the event for the Slack webhook.

**Steps to reproduce**:
- Setup a Slack webhook with the issue tracker checked
- Create an issue
  - It should fire the issue created event
- Create a commit, with a keyword to close the issue (e.g. "Close #42)
  - No event was fired

**Comment by kounoike** [comment]
I tried to solve this issue, but I gave up. Because, the commit pushed from **ssh** also should fires webhook and plugin's hook. But plugin's hook requires `gitbucket.core.controller.Context` (which requires `HttpServletRequest`). I can't create `Context` in ssh session.
@takezoe Do you have any idea?
