### ISSUE TITLE
Keeping commit comments visible after rebase

### ISSUE THREAD

**Issue by imeszaros** [gitbucket/gitbucket#1897]
**Impacted version**: 4.22.0
**Deployment mode**: standalone

Consider the following scenario:

A PR is created for a change. Then a long going conversation is started on the PR, mentioning specific lines in various commits. In the meanwhile, the master branch is updated by new commits from other PRs. When the discussion is over on the PR mentioned before, turns out that there are some conflicts and the PR cannot be merged with GitBucket's online interface. The developer then rebases the PR-branch on master, so it can be merged successfully.

The problem is that after this scenario the PR comments that were addressing specific lines in specific commits are not visible anymore (although on the PR listing page the comment counter still counts them).

In my opinion it would be helpful if these comments could be still read, since they may contain important change requests or discussion that are the integral history of the PR and the development process.

To indicate that the *reference* to the specific line is no longer valid, the comment could be faded out or may be collapsed somehow, or other visual indication could be used.

**Comment by kryskool** [comment]
Hi @imeszaros 

When you rebase, the commit hash can be changed, and I think that's the cause of the disappearance of the comment

**Comment by imeszaros** [comment]
Hi @kryskool! Certainly. But in the `COMMIT_COMMENT` table the issue ID is also recorded, so GitBucket would be able to show these comments, only the hyperlink to the "old" commit must be erased or marked as disabled.

**Comment by takezoe** [comment]
In GitHub, such comments are displayed as folded. It would be nice if we can make it in GitBucket as well.

**Comment by imeszaros** [comment]
I'll try to take care about this.

**Comment by yaroot** [comment]
To me, showing comments without related code is kinda useless, especially if you have some experiences with dedicated code review tools (gerrit, reviewboard, ..., but these are not easy to use and get adopted).

Github show comments with all obsolete code folded, which means that they save the code somewhere with the comments.

<img width="842" alt="" src="https://user-images.githubusercontent.com/42634/37857450-0a15d048-2f36-11e8-8e6c-31424e202a16.png">

There are other ways, we could assign each update to PR to a special ref `refs/pr-history/<pr>/<n>`, and save the ref alone with comments. But this would likely use some extra disk space without people realize it, but since other tools are doing this we should consider it.
