### ISSUE TITLE
Question: Connecting GitBucket to VisualStudio

### ISSUE THREAD

**Issue by ApertureDevelopment** [gitbucket/gitbucket#2071]
Hello,

Does someone know how I can connect a existing VisualStudio project to a GitBucket server?

**Comment by SIkebe** [comment]
Is that project already version controled by Git?
Then, this might help you.
https://blog.mzikmund.com/2018/04/adding-github-upstream-remote-in-visual-studio/

**Comment by takezoe** [comment]
@ApertureDevelopment I'm not sure about VisualStudio, but doesn't the Git support in VisualStudio work for GitBucket managed projects?

By the way, I hope you to ask at the [gitter room](https://gitter.im/gitbucket/gitbucket) before creating an issue if you have such questions according to the [support guideline](https://github.com/gitbucket/gitbucket/blob/master/.github/SUPPORT.md) because we want to use here for tracking issues and tasks.

**Comment by takezoe** [comment]
Close because this issue seems to have no potential to be a cause of issues or feature requests.
