### ISSUE TITLE
How to move GITBUCKET_HOME location

### ISSUE THREAD

**Issue by Servh37** [gitbucket/gitbucket#2095]
Hi,

i just wanted to ask how i can go about moving the GITBUCKET_HOME,

as i will like to move the repo store location to a nfs share or to a different location.

can you please advise how i can go about this.

Regards

**Comment by takezoe** [comment]
If you run GitBucket as standalone mode, you can specify GITBUCKET_HOME by `--gitbucket.home` option as explained in [README](https://github.com/gitbucket/gitbucket#installation). Otherwise, like deploy on the servlet container, you can do it by a system property: `gitbucket.home` or an environment variable: `GITBUCKET_HOME`.

Anyway, please send question to [gitter room](https://gitter.im/gitbucket/gitbucket) before creating an issue according to the [guideline](https://github.com/gitbucket/gitbucket/blob/master/.github/SUPPORT.md).
