### ISSUE TITLE
How i can run application over https

### ISSUE THREAD

**Issue by lakshykar** [gitbucket/gitbucket#2121]
What are the settings i need to do to run gitbucket on https.
Where to configure port, certificate etc?

**Comment by McFoggy** [comment]
in order to serve gitbucket over https you need either a reverse proxy (nginx, caddy, httpd, ...) or a servlet container supporting https (tomcat, wildfly, ...)

If you choose the reverse proxy (RP) solution, the RP will serve the traffic in https and proxy requests towards gitbucket in http.
Please look at basic reverse proxy in the [wiki](https://github.com/gitbucket/gitbucket/wiki) and then go to the reverse proxy documentation on how to setup TLS.
