### ISSUE TITLE
Git protocol v2?

### ISSUE THREAD

**Issue by dkowis** [gitbucket/gitbucket#2131]
Not a problem, but apparently [git has a v2 binary protocol ](https://opensource.googleblog.com/2018/05/introducing-git-protocol-version-2.html) now, that performs significantly better.

I assume it would need to be supported by the underlying git implementation that gitbucket is using. Just creating this issue, because it'd be nice to have whenever it shows up there.

**Comment by aadrian** [comment]
@dkowis GitBucket is using JGit , but AFAIK it's support for Git v2 is quite recent and not complete yet https://projects.eclipse.org/projects/technology.jgit/releases/5.0.0

Since we already have JGit 5.0.2 https://github.com/gitbucket/gitbucket/blob/master/build.sbt#L9 , basically everything should be there to give it a try.

**Comment by takezoe** [comment]
We should discuss about this topic at #2012.
