### ISSUE TITLE
Provide common Single Sign On options

### ISSUE THREAD

**Issue by kastork** [gitbucket/gitbucket#227]
Some resources
- Pac4j, example with Play framework, https://github.com/leleuj/play-pac4j
- Or maybe Spring security.

My interest, Jasig CAS, is particularly important in academic environments
others have asked for social media based SSO

**Comment by aadrian** [comment]
SSO with JSON Web Tokens? 
https://jwt.io/

**Comment by marshalhayes** [comment]
I'm unsure of the technical/security limitations with pass-through authentication but that might be something to look into.

I know browsers can, for example, pass a user's Windows credentials to a trusted site without any user action really. IIS supports this natively I'm pretty sure. It might be as simple as:
1. Enable pass through authentication on the IIS site running GitBucket
2. When a user passes their credentials, capture it and check it against the LDAP server
3. If their authorized, login them in. Otherwise, leave them on the login page.

Now in terms of which libraries/tools to use to capture these credentials I am unsure of.

**Comment by takezoe** [comment]
OpenID Connect has been supported.
