### ISSUE TITLE
Importing repositories from gitbucket

### ISSUE THREAD

**Issue by prabhakarlad** [gitbucket/gitbucket#2313]
My h2 database went corrupt and fails to recover. I want to import the git repositories from .gitbucket/repositories to new one. Is there any simpler way of doing it ?

**Comment by takezoe** [comment]
GitBucket has bare repositories under .gitbucket/repositories. You must do first is copying them to anothet location for backup. Then you can create repositories on new GitBucket instance and push backup repositories to new GitBucket instance.

Anyway, we highly recommend to take a backup and use MySQL/PostgreSQL instead of default H2 database if your GitBucket instance is critical for you.

**Comment by prabhakarlad** [comment]
I have now backed up the repositories, but now when I create a new reposoty and try and push I get following errors:

error: could not lock config file config: Permission denied
fatal: Could not set 'remote.gitbucket.url' to 'http://rlvsvn/git/prabhakarlad/gitbucket.git

**Comment by takezoe** [comment]
Your error message is saying "Authentication failed".

**Comment by takezoe** [comment]
Any updates? Can I close the issue?

**Comment by takezoe** [comment]
Since there are no updates, I'm going to close this issue.
