### ISSUE TITLE
Preview doesn't work when editing HTML file

### ISSUE THREAD

**Issue by zexxar** [gitbucket/gitbucket#2384]
Hi,

I think there is a bug with the preview when editing HTML files. Because when you click on the preview it shows nothing.

![html](https://user-images.githubusercontent.com/4499859/66038546-b3c95900-e512-11e9-9817-cb037583fe96.png)
![preview](https://user-images.githubusercontent.com/4499859/66038547-b3c95900-e512-11e9-9e70-73ca7a90c96e.png)

Thank you.

**Comment by takezoe** [comment]
HTML rendering is disabled because it causes cross-site scripting.

**Comment by aadrian** [comment]
> Actually, this is not a bug. Preview rendering is available for Markdown and other formats supported by installed plugins. It doesn't work for HTML.

The [pages-plugin](https://github.com/gitbucket/gitbucket-pages-plugin) plug-in is allowed to render HTML. 

Without the HTML preview, the users will do allot of small commits, and changes, since they can't see what they're really doing.

> I think HTML preview shouldn't be supported without restriction because it can cause cross-site scripting if HTML contains JavaScript.

IMHO just like in the case of the 'pages-plugin', a subdomain (+ iframe) and the section https://github.com/gitbucket/gitbucket-pages-plugin#security-panic-mode would simply do it.

**Comment by takezoe** [comment]
> The pages-plugin plug-in is allowed to render HTML.

Yes. Though GitBucket itself doesn't support HTML rendering due to prevent cross-site scripting, users can use pages-plugin if they need to host HTML on GitBucket. It's can be disabled, so users can use it at their own risk.

**Comment by takezoe** [comment]
I close this issue since this is designed behaviour.
