### ISSUE TITLE
Can't login if change base URL

### ISSUE THREAD

**Issue by sampidevkit** [gitbucket/gitbucket#2436]
I installed gitbucket 4.33.0 on Windows 10. I registed an address http://mygit3775.ddns.net on no-ip server to redirect to my network because it's a dynamic IP network. Then I change base URL of gitbucket to http://mygit3775.ddns.net, I can access to my gitbucket anywhere but I can't login.
Could you help me fix it?

**Comment by takezoe** [comment]
You can modify `~/.gitbucket/gitbucket.conf` directly to fix the configuration or just remove this file can get your environment back to default.

**Comment by sampidevkit** [comment]
I can access homepage, but can't login, waiting forever.
[https://drive.google.com/open?id=1uL7A6QROBlvATfoGEsI41sta5WYmUgH_](url)

**Comment by Sherpard** [comment]
before you set a basepath you must be sure that you can reach your gitbucket instance trough your DNS. (i've experienced this issue also, but it was due to not being able to reach the DNS)

anyway @takezoe is right, you can manually edit gitbucket.conf to change whatever (it's a pretty simple format) or you can plain delete it to get back to default.

**Comment by sampidevkit** [comment]
Thank you.
I think I solved it. Something wrong in no-ip server. Instead of redirecting mygit3775.ddns.net to IP and port, I redirect only IP.
