### ISSUE TITLE
problem last files commit comment and update date after update from 4.33 to 4.34

### ISSUE THREAD

**Issue by SaraDark** [gitbucket/gitbucket#2507]
**Impacted version**: 4.34.0
 standalone app with nginx proxy

**Problem description**:
- not show commit comment - on files list in repository view
- not show commit date/last update - on files list in repository view

Hi, i have many repos on gitbucket, after update from 4.33.0 to 4.34.0 on one my repo where is lot of lfs and normal git commits i dont see last commit message and date in file/dir list on view files in repo, main view. I return to 4.33.0 and problem sloved. Problem is only on version 4.34.0.

**Comment by takezoe** [comment]
https://github.com/gitbucket/gitbucket/pull/2466

> Introduce the upper limit for the number of files to retrieving commit info

This might affect you. If the number of files in a directory is >= 100, GitBucket doesn't fetch detailed information of the commit in order to avoid high workload. However, if the machine has enough resource, this threshold may be too tight.

I'm thinking that making this threshold configurable.

**Comment by SaraDark** [comment]
Good to known, option in configuration seans cool :) :+1:
