### ISSUE TITLE
Demo without password and username?

### ISSUE THREAD

**Issue by ShalokShalom** [gitbucket/gitbucket#2712]
https://gitbucket.herokuapp.com/

Did anyone of you use this test instance?

There is an empty screen and a login button, that lefts me without a password and username to put in.

How is this supposed to help?

**Comment by skullwritter** [comment]
It was root:root now I don't know what it is

**Comment by ShalokShalom** [comment]
How unprofessional

**Comment by aadrian** [comment]
@ShalokShalom That demo gets reset to a standard installation every few hours, but it gets vandalized from time to time.

If it's a fresh installation than with root/root you can login and use it like you would have when you start it locally with `java -jar gitbucket.war`  https://gitbucket.github.io/https://gitbucket.github.io/

Not sure what do you consider "unprofessional" there.

**Comment by ShalokShalom** [comment]
Where is root/root mentioned on the website?

**Comment by onukura** [comment]
It is mentioned on README.
https://github.com/gitbucket/gitbucket#gitbucket----
> You can try an online demo (ID: root / Pass: root) of GitBucket, and also get the latest information at GitBucket News.

**Comment by ShalokShalom** [comment]
How about mentioning it in tbe demo login screen, so people dont need to search for it?

**Comment by aadrian** [comment]
> How about mentioning it in the demo login screen, so people dont need to search for it?

@ShalokShalom  that would defy the whole point of a login screen, wouldn't it? :) 

Also note that the version that runs there on Heroku, is exactly the **same** that runs when you start it with `java -jar gitbucket.war` on your own servers/machines , so it's not a very wise move to advertise the root user on the login page either :) .

**Comment by ShalokShalom** [comment]
Thisnis a demo instance. People cant login. How is that so hard to understand?

**Comment by takezoe** [comment]
We currently deploy the released version of war file to the demo site too and of course, the released version of war file doesn't show admin username and password. We can show them if we create a war file dedicated for the demo site, but we didn't have room to do that because the demo site was originally launched by one voluntary collaborator. I would thank for his effort even if there is some lack of user experience. It would be better than nothing, I believe.

**Comment by ShalokShalom** [comment]
Half bad user experience is NOT better than nothing. Nothing lets room for the real good solutions, and lets us not waste time on such ones as this. Either do it good or dont do it at all.

**Comment by takezoe** [comment]
Then, we will close the demo site. Thank you.

**Comment by ShalokShalom** [comment]
Close the project, same logic.

**Comment by takezoe** [comment]
Yeah, that makes sense to me. What you are saying is that.

**Comment by takezoe** [comment]
To be honest, I thought the demo site will help users to touch GitBucket without installation (I thought finding admin username and password from README is much easier than installing GitBucket), but it actually might have wasted someone’s time. I’m really sorry about it.

**Comment by ShalokShalom** [comment]
Just create a new site, put pass/user on it and the link.

**Comment by takezoe** [comment]
Hmm... What’s the difference from the current situation? We have username and password right below the link to the demo site on README. I think it’s the most accessible place for users.

**Comment by ShalokShalom** [comment]
I am talking about the homepage itself.
I have never seen the hint on Github, I went straight to the homepage and clicked on the demo.

**Comment by takezoe** [comment]
Is this page? https://gitbucket.github.io

I think this page is much harder to reach than GitHub repository for average users.

**Comment by ShalokShalom** [comment]
No, just creating an intermediate page, between the homepage and the actual instance.

**Comment by McFoggy** [comment]
@takezoe you should probably not waste your time with such an endless discussion.

@ShalokShalom if you want, you can probably contribute something _"less unprofessional"_ instead of criticize what the community is doing. Looking at your profile you are a specialist in typos commits ; this time it will be a bit more.

If you want provide a PR on https://github.com/gitbucket/gitbucket.herokuapp.com which serves to deploy the test application. I am sure that digging a bit in gitbucket you will be able to set it up so that the message appears on the main deployed page.

hint 💡 :  a relatively easy way would be to provide a "site notification" like the following

![image](https://user-images.githubusercontent.com/1119660/112502767-a3521180-8d8a-11eb-9b78-86ac2847933e.png)

You could generate/provide a default config file containing that site notification for the heroku app.

We promise we'll study very carefully the PR you're going to submit.

**Comment by ShalokShalom** [comment]
https://github.com/gitbucket/gitbucket/issues/2712#issuecomment-805669282

**Comment by ShalokShalom** [comment]
And again: I have zero intention, to contribute to a project, that doesn't get the essentials right. 
Where else got such design decisions made, that put the user last?
You could easily just create a landing page and then list the details there, and put the link below. 

But that this is not done, is because the _user experience_ is not of any interest here.
Since when you put yourself into the position of someone who is new to the project, you can see how it is likely to _start at the homepage_, which is really not that much off the charts. 

And then you face a login screen, you dont know the details for, and need to go digging.

**Comment by takezoe** [comment]
Again, we already have a landing page.
https://gitbucket.github.io

I cannot understand how adding another landing page improve the situation.
