### ISSUE TITLE
Support merging pull requests via commit

### ISSUE THREAD

**Issue by calid** [gitbucket/gitbucket#663]
**Expect**
A merge commit with the message `Merge pull request #42 from foo/bar` will close pull request `#42` 

**Actual**
Merge commit has no effect and the pull request remains open

**Reproduce**
Create a branch with some changes, open a pull request, but then instead of closing the PR via the UI, instead merge locally and push a commit identical to what the UI would produce.  This has no effect.

Github supports closing pull requests via commit, and it would be nice if gitbucket emulated this behavior.  Perhaps by also supporting the shorter `Merge #42` form in addition to the longer `Merge pull request #42`.

**Comment by McFoggy** [comment]
@takezoe do you think you'll be able to work on this for 3.5? It would be really great to see it so that it becomes effort less to keep history of projects clean. Of course we can leave with the manual `close`after the merge occured but it is so convenient to use keywords actions on commit.

I'd also suggest to identify what keywords can be used to do so.
I started a wiki page to reference that: [How to Close Reference issues & pull request](https://github.com/takezoe/gitbucket/wiki/How-to-Close-Reference-issues-&-pull-request)

**Comment by takezoe** [comment]
@McFoggy Sorry, we want to put off this issue to 3.6.

**Comment by McFoggy** [comment]
I understand no problem.

**Comment by McFoggy** [comment]
I do not know what are the expectations for this story ; but now you can close PR in github just by pushing to the destination branch of the PR without having to provide any 'command' in the commit comment.

**Comment by takezoe** [comment]
Once remove milestone.

**Comment by takezoe** [comment]
@kounoike Indeed. Thanks for your work!
