### ISSUE TITLE
user email does not display on profile page

### ISSUE THREAD

**Issue by calid** [gitbucket/gitbucket#673]
Even though I've set an email in my profile, it doesn't actually display on my profile page:

![selection_033](https://cloud.githubusercontent.com/assets/494405/6803230/38911550-d204-11e4-90f4-fc0923bf4c5a.png)

![selection_034](https://cloud.githubusercontent.com/assets/494405/6803235/3eb2438c-d204-11e4-8e77-66bd3b7fd855.png)

**Comment by mann-ed** [comment]
This is an easy change in src/main/twirl/gitbucket/core/account/main.scala.html
@if(!Option(account.mailAddress).getOrElse("").isEmpty){
           	<div><i class="icon-envelope"></i> <a href="mailto:@account.mailAddress">@account.mailAddress</a></div>
        }
![mailaddress](https://cloud.githubusercontent.com/assets/4854757/7161665/da9b8b70-e355-11e4-95d1-9717c976def6.png)


I created a pull request. but it has another change for version display. Being new to this project not sure how much traction i will get. I did not do a great job on my first pull request. :-D

**Comment by takezoe** [comment]
I don't know whether it should be displayed as public information. It might be better to choose whether it's displayed by users themselves.

**Comment by aadrian** [comment]
> I'm not sure whether it should be displayed as public information
> It might be better to choose whether it's displayed by users themselves.

IMHO GitBucket should not adopt here the same strategy as GitHub, since it's target users are small teams in company intranets/Internet and small companies that can't use (or afford) the Enterprise version.

That's why, even if allot of functionality needs to be there (e.g. for users to make them public), maybe some other **sensible defaults** would help **our** target users more:
 - private repositories as default
 - email visible only by admins (or maybe other group members) as default
 - groups the user belongs to not be a public information as default
 - the tab to be called "Activity" not "Public Activity" and have unlimited data (since audit is important). "Public Activity" would be something that the user could activate if it wishes to show.

In allot of our installations we had to block allot of the above URLs from the WebServer (Nginx/Apache) in order to prevent users to expose company information that is not supposed to be publicly visible.
