### ISSUE TITLE
Encrypt the h2 database.

### ISSUE THREAD

**Issue by hansgru** [gitbucket/gitbucket#68]
Add support to encrypt the database. H2 fully supports this:
http://www.h2database.com/html/features.html#file_encryption

**Comment by aadrian** [comment]
It's much simpler if this option is done at build time (as an alternative build), so that the ```gitbucket\src\main\resources\database.conf``` has the correct URL with the required encryption params.

The user could of course build GitBucket from the sources and change the URL as described in the link above, but most users will simply just deploy the ```gitbucket.war``` file.

**Comment by nazoking** [comment]
since version 4.0 (30 Apr 2016),  you can use [GITBUCKET_HOME/database.conf](https://github.com/gitbucket/gitbucket/wiki/External-database-configuration) for database option setting.

**Comment by aadrian** [comment]
@nazoking yes, but this needs to be documented since it's not an obvious feature.

**Comment by nazoking** [comment]
@aadrian can you update our wiki page?

**Comment by aadrian** [comment]
> can you update our wiki page?

Done: https://github.com/gitbucket/gitbucket/wiki/External-database-configuration#database-encryption

**Comment by nazoking** [comment]
@aadrian thank you! 👍
