### ISSUE TITLE
SSH base URL configuration should be separated from HTTP base URL

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#734]

**Comment by Cy4n1d3** [comment]
This would be great, I also need to run on a different port than 80 (or 8080) and thus I'm unable to enable SSH right now due to the port-stripping on base url.

**Comment by ritschwumm** [comment]
not exactly trivial - the code using baseUrl and - derived from that - ssh urls is quite a mess.
i'm trying to get this cleaned up so i can proceed with #971. 

current plan:
* use a case class instead of a String for a baseUrl
* enhance this class to include an ssh-baseUrl
* move full-url generation and calculations in one place

does this make sense to you?

**Comment by ritschwumm** [comment]
i guess this can be closed now
