### ISSUE TITLE
Set http header for browser cache

### ISSUE THREAD

**Issue by nazoking** [gitbucket/gitbucket#777]
Please set http header for browser cache control. For examples ETag , Last-Modified, Expires.

Especially, under /assets, and avater.

( I looked for an effective method in scalatra and jetty , but I did not know .. ;)

**Comment by haarp** [comment]
Yes, please do. I notice that avatars, for example, are always reloaded on every page refresh. Something is disabling the browser cache on Gitbucket.

**Comment by haarp** [comment]
If you're running an Apache reverse proxy in front of Gitbucket, you can work around this bug with:

        <LocationMatch "_avatar$">
                Header set Cache-Control "max-age=86400, public"
        </LocationMatch>

It really only seems to affect avatars, all other resources are cache properly by the browser (HTTP 304)

**Comment by kounoike** [comment]
In current version of GitBucket (4.10 + some patch) and chrome, /assets/* are cached. But /plugin-assets not cached.

![cache](https://cloud.githubusercontent.com/assets/6997928/23854817/7288b38e-0836-11e7-84f2-9c0cf5349748.png)

I read HTTP session by Fiddler, /assets/* has Last-Modified header and Date header. /plugin-assets/* has Date header only.
By #1489, some CSS move from /assets to /plugin-assets. It makes bad feel to user's experience?

**Comment by kounoike** [comment]
|Browser|/assets|/plugin-assets|_avatar|
|---------|-------|---------------|--------|
|Chrome|cached|not cached|not cached|
|firefox|cached|not cached|not cached|
|IE 11|not cached|not cached|not cached|

/plugin-assets served by PluginAssetsServlet, then it can easy to add some HTTP headers.
_avatar served by AccountController, I don't know how to add HTTP headers. Because http://www.scalatra.org/2.4/guides/http/requests-and-responses.html is down now.

**Comment by kounoike** [comment]
Oh... my IE's "常にサーバから更新する" (always reload from servers) setting is checked.
I removed this check, /assets/* are cached.

And I add `resp.setHeader("Cache-Control", "max-age=86400")` to PluginAssetsServlet, /plugin-assets also cached.

**Comment by takezoe** [comment]
Fixed in #1491
