### ISSUE TITLE
Deploy gitbucket-assembly.jar into Maven central or CDN

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#935]

**Comment by ritschwumm** [comment]
see https://github.com/gitbucket/gitbucket/pull/1065 for some more details

**Comment by McFoggy** [comment]
any info on that? amatareas.sourceforge.jp is really slow from europe.

**Comment by takezoe** [comment]
@McFoggy Requested `io.github.gitbucket` group id to sonatype with @tanacasino and your account I found in sonatype JIRA: https://issues.sonatype.org/browse/OSSRH-20869

I would like to publish other libraries of GitBucket organization such as markedj, solidbase and scalatra-forms to Maven central repository, not only `gitbucket-assembly.jar`.

**Comment by McFoggy** [comment]
@takezoe for sonatype once you have register a domain then you can pubish as many artifacts as you want within this domain (or any subdomain). I did exactly that for my projects under [oss.brouillard.fr](http://oss.brouillard.fr/). But I could do it because I own the domain `brouillard.fr`. 
It is perhaps time for gitbucket organization to collect some money at least to pay for a domain. If we host only static content, github pages can be sufficient.

**Comment by McFoggy** [comment]
Without a domain, once you have the green light for `io.github.gitbucket`, then you will be able to deploy also any other artifact if an only if its groupid is `io.github.gitbucket` or any child of it `io.github.gitbucket.libraries`, `io.github.gitbucket.markedj`.

**Comment by takezoe** [comment]
@McFoggy I know. I already have some other group ids in sonatype.

I was looking for domain for GitBucket few years ago. However I couldn't get suitable domain such as `gitbucket.com`. Unfortunately, they had been acquired to other people.

Anyway, I will publish all jars to the Maven central repository after my request is accepted. Please wait for a moment.

**Comment by McFoggy** [comment]
@takezoe any chance to finally have the gitbucket artifacts deployed to central?
