### ISSUE TITLE
Sync Gitbuckets?

### ISSUE THREAD

**Issue by hansgru** [gitbucket/gitbucket#97]
Hi,

I would like to have a few instances of GitBucket running on different machines. How would one keep those installations in sync while the systems still run ?

regards.

**Comment by aadrian** [comment]
Any movement on this issue? 

I'm also having this requirement now, and unfortunately I'm having no idea how to solve the problem with GitBucket :( .

It doesn't seems to be something solvable with a plug-in either, since plug-in support would need to cover really every aspect and state of the application.

Also the new support for further DBs doesn't seem to make stuff easier.
